# This Makefile is included by the subproject ukernels.

SHELL 	 :=/bin/bash
APP_FLAGS ?=
SOURCES 	 += ../common/cctimer.c ../common/barrier.c ../common/cclfsr.c

OBJECTS ?= $(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(patsubst %.cc,%.o,$(SOURCES) ) ) )

include ../arch/riscv/Makefile.mk


# Build targets
all: $(TARGET)

$(TARGET): $(OBJECTS)
	if $(foreach source,$(OBJECTS),[ $(source) -nt $(TARGET) ] ||) 1; \
	then $(CC) $(CFLAGS) $^ -o $@ $(LD_FLAGS) $(LD_LIBS); \
	fi

run: $(TARGET)
	./$(TARGET) $(APP_FLAGS)


clean:
	-rm -f *.o *.d ../common/*.o $(TARGET)

